repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args:
          - "-l=120"
          - "--multi-line=3"
          - "--tc"
          - "--up"
          - "--force-grid-wrap=0"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
        exclude: (charts/*|.gitlab-ci.yml)
      - id: debug-statements
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-use-type-annotations
  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
      - id: black
        args:
           - "--line-length=120"
        language_version: python3.9
